# Generated by Django 5.1.6 on 2025-02-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='token',
            new_name='device_id',
        ),
    ]
